---
- hosts: localhost
  vars_files:
    - /home/ansible/keys/aws-access.yml
  become: yes  
  vars:
    ec2_image_id: ami-01816d07b1128cd2d
    sg_name: httpd-server-sg
    ec2_ssh_key_name: ansible-control-key
    subnet_id: subnet-09e6eed71b90d7c13 
    instance_small: t2.small  
  tasks:
    - name: create a sg for instances
      ec2_group:
        aws_access_key: "{{ ACCESS_ID }}"
        aws_secret_key: "{{ SECRET_ID }}"
        region: "{{ REGION }}"
        name: "{{ sg_name }}"
        description: sg for ansible nodes
        state: present        
        rules:
          - proto: tcp
            ports:
              - 80
              - 443
              - 22
            cidr_ip: 0.0.0.0/0

    - name: create ssh key for instance based on the keys available at control
      ec2_key:
        aws_access_key: "{{ ACCESS_ID }}"
        aws_secret_key: "{{ SECRET_ID }}"
        region: "{{ REGION }}"
        name: "{{ ec2_ssh_key_name }}"
        key_material: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"        
        state: present 
        wait: yes

    - name: create an ec2 instance ansible-node2
      ec2_instance:        
        access_key: "{{ ACCESS_ID }}"
        secret_key: "{{ SECRET_ID }}"  
        image_id: "{{ ec2_image_id }}"
        instance_type: "{{ instance_small }}"
        region: "{{ REGION }}"
        name: node3
        key_name: "{{ ec2_ssh_key_name }}"
        security_group: "{{ sg_name }}"
        network:
          assign_public_ip: yes
        state: present  
        tags:
          app: web
        vpc_subnet_id: "{{ subnet_id }}"
        wait: yes    


    - name: gather insances info
      ec2_instance_info:
        access_key: "{{ ACCESS_ID }}"
        secret_key: "{{ SECRET_ID }}" 
        region: "{{ REGION }}"
        filters:
          "tag:app": web
          instance-state-name: ["running"]
      register: web_app_instances

    - name: extract public IP addresses of the instances
      set_fact:
        public_ips: "{{ web_app_instances.instances | map(attribute='public_ip_address') | list }}"

    - name: view public IP addresses
      debug:
        var: public_ips

    - name: create a dynamic host to inventory
      add_host:
        hostname: "ec2-user@{{ item }}"
        groupname: webhosts
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
      loop: "{{ public_ips }}"

-   hosts: webhosts
    become: yes
    tasks:

    -   name: wait ssh connection
        wait_for_connection:
            delay: 5
            timeout: 90

    -   name: install httpd
        dnf:
            name: httpd
            state: latest

    -   name: install git
        dnf:
            name: git
            state: latest
    
    -   name: git checkout the website
        git:
            dest: /var/www/html
            repo: https://github.com/linuxacademy/content-introduction-to-ansible.git

    -   name: Start Apache Service
        service:
            name: httpd
            state: started
            enabled: yes


                               